version: 2
updates:
  - package-ecosystem: npm
    directory: /typescript
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /python
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /typescript
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /python
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
